name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']  # Adjust versions if incompatible
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml # Add any required PHP extensions here
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: composer install --prefer-dist --no-progress --no-suggest # Optimize installation
      - run: composer validate --strict # Validate composer.json with strict mode
      
      # Check for necessary files before running tests and analysis
      - name: Check for necessary files
        id: check_files
        uses: thebinaryfelix/check-file-existence-action@v1
        with:
          files: 'composer.json, composer.lock, phpstan.neon'

      - name: Run PHPUnit
        run: vendor/bin/phpunit --log-junit junit.xml
        if: steps.check_files.outputs.exists == 'true'

      - name: Static Analysis (PHPStan)
        run: vendor/bin/phpstan analyse
        if: steps.check_files.outputs.exists == 'true'

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: junit-results
          path: junit.xml