name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']  # Adjust versions if incompatible
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml # Add any required PHP extensions here
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }} # Use double asterisks for broader matching
          restore-keys: ${{ runner.os }}-composer-
      - run: composer install --prefer-dist --no-progress --no-suggest # Optimize installation
      - run: composer validate --strict # Validate composer.json with strict mode
      - name: Run PHPUnit
        run: vendor/bin/phpunit --log-junit junit.xml || true # Prevent failure if tests fail (optional)
        if: ${{ fileExists('composer.json') && fileExists('composer.lock') }}
      - name: Static Analysis (PHPStan)
        run: vendor/bin/phpstan analyse || true # Prevent failure if analysis fails (optional)
        if: ${{ fileExists('phpstan.neon') }}
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: junit-results
          path: junit.xml